### PR TITLE
Circular dependency if enabler references own layer or class

### PR DESCRIPTION
**Pull request by Julusian**
* **What is the current behavior?** (You can also link to an open issue here)
Circular dependency exception is thrown, causing the timeline resolve to fail

* **What is the expected behavior?**
As they are very loose selectors, it would be preferable if they could simply ignore the object initiating it.

This behaviour would be useful to be able to insert an object after each other object on a layer. Such as to insert a static titlecard or endcard for a video

* **Other information**:

### CODE REVIEW

**Comment by nytamin** [comment]
Good point!
There is a challenge to solve, though:

What should happen if there are multiple self-layer-referencing objects?
i.e:
```
[{
	id: 'video0',
	layer: '0',
	enable: {
		start: 0,
		duration: 8,
		repeating: 10
	},
	content: {}
},{
	id: 'insert1',
	layer: '0',
	enable: {
		// Play for 2 after each other object on layer '0'
		start: '$0.end',
		duration: 2
	},
	content: {}
},
{
	id: 'insert2',
	layer: '0',
	enable: {
		// what happens now?
		start: '$0.end',
		duration: 2
	},
	content: {}
}]
```

Should this result in _insert1_ and _insert2_ both being added, after eachother? If yes; what should determine which order they should have?

**Comment by Julusian** [comment]
The only way I can see that case being sane and predictable is for each object to ignore every other self-referencing object, not just itself. I think this will work for both layers and classes.

This would mean that `insert1` and `insert2` are both evaluated, but would end up with the same instance times immediately after `video0`. Which one ends up in the state will be determined by priorities as usual. While not immediately useful behaviour by itself, by combining with a timed offset in `enable.start` or further filtering by class it would be useful.

I can see is that if they do try to insert after each other it could easily form an infinite loop, and kill the timeline from both computational and memory use.

**Comment by nytamin** [comment]
That might be a good ide, I'll try that! :)

**Comment by nytamin** [comment]
@Julusian I've changed the tests a bit and implemented a proposed fix, could you review it and let me know if you think that it will solve your issue?

**Pull request merged**
